### ISSUE TITLE
Project doesn't run!

### ISSUE THREAD

**Issue by skywalkerbd** [JaeShinJun/jirbnb#1]
Check this screenshot. please fix this problem

![Screenshot_4](https://user-images.githubusercontent.com/71786323/94052338-9dd73700-fdfa-11ea-86af-2dd47bd1bad8.png)

**Comment by JaeShinJun** [comment]
You have to create your own secret key for Django.

https://github.com/JaeShinJun/jirbnb/blob/013517e240dd8083e133410ce2acec36e5be624c/config/settings.py#L41

Check this part in config/settings.py.
